### ISSUE TITLE
Thank you very much and Just a quick question.

### ISSUE THREAD

**Issue by JargonMac** [hodzanassredin/NFastText#2]
Firstly I would like you so very much for taking the time in creating **NFastText**. Although I don't see any updates for a couple of months its been a joy working with NFastText. 

I have a quick question I hope you don't mind answering.

One of the advantages of FastText over Word2Vec and GloVe has been the capability of generating word vectors for out-of-vocabulary words. Has the same been implemented in **NFastText**?

Once again I would like to thank you for time and wish best of luck in all future endeavors.

**Comment by hodzanassredin** [comment]
I think it is better to ask in FastText group https://www.facebook.com/groups/1174547215919768/
